[package]
name = "web-rwkv-derive"
version = "0.2.0"
edition = "2021"
authors = ["Zhenyuan Zhang <cryscan@umich.edu>"]
license = "MIT OR Apache-2.0"
description = "An implementation of the RWKV language model in pure WebGPU."
homepage = "https://github.com/cryscan/web-rwkv"
repository = "https://github.com/cryscan/web-rwkv"
keywords = ["deep-learning", "language", "model", "rwkv"]
categories = ["science", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2"
quote = "1"

[lib]
proc-macro = true
